vim.api.nvim_create_user_command("GitCheatSheet", function()
  vim.cmd("enew")
  local buf = vim.api.nvim_get_current_buf()

  -- Scratch buffer settings
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].filetype = "markdown"

  local lines = {
    "# Git Cheat Sheet (Expanded)",
    "",
    "Tip: use `git help <cmd>` or `git <cmd> --help` for details.",
    "",
    "------------------------------",
    "## Setup & Config",
    "",
    "### Identity",
    "git config --global user.name \"Your Name\"",
    "git config --global user.email \"you@example.com\"",
    "git config --global user.signingkey <keyid>           # GPG/SSH signing",
    "git config --global commit.gpgsign true               # always sign commits",
    "",
    "### Useful defaults",
    "git config --global init.defaultBranch main",
    "git config --global pull.rebase true                  # default pull behavior",
    "git config --global rebase.autoStash true             # stash while rebasing",
    "git config --global fetch.prune true                  # prune deleted remote branches",
    "git config --global rerere.enabled true               # reuse conflict resolutions",
    "",
    "### Aliases (optional ideas)",
    "git config --global alias.st status",
    "git config --global alias.co checkout",
    "git config --global alias.sw switch",
    "git config --global alias.br branch",
    "git config --global alias.lg \"log --oneline --graph --decorate --all\"",
    "",
    "### Inspect config",
    "git config --list",
    "git config --global --list",
    "git config --show-origin --list                       # where config values come from",
    "",
    "------------------------------",
    "## Create / Clone / Initialize",
    "",
    "git init                                              # start repo in current dir",
    "git init <dir>",
    "git clone <url>",
    "git clone <url> <dir>",
    "git clone --depth 1 <url>                              # shallow clone",
    "git clone --branch <branch> <url>                      # clone a specific branch",
    "",
    "------------------------------",
    "## Status / Inspect / History",
    "",
    "### Working tree",
    "git status",
    "git status -sb                                        # short + branch",
    "git diff                                              # unstaged changes",
    "git diff --staged                                     # staged changes",
    "git diff <commit>..<commit>                           # compare commits",
    "git diff <branch>...<branch>                          # symmetric diff",
    "",
    "### Commit history",
    "git log",
    "git log --oneline --graph --decorate --all",
    "git log -p                                            # patch per commit",
    "git log --stat                                        # file stats per commit",
    "git show <commit>",
    "git show <commit>:<path>                              # file content at commit",
    "",
    "### Search history",
    "git blame <file>",
    "git blame -L <start>,<end> <file>                     # blame line range",
    "git grep \"pattern\"                                  # search tracked content",
    "git log -S \"string\"                                 # pickaxe search (string changes)",
    "git log -G \"regex\"                                  # regex diff search",
    "",
    "### Inspect objects",
    "git rev-parse HEAD                                    # commit hash",
    "git cat-file -p <object>                              # show object",
    "git ls-tree -r HEAD                                   # list files at commit",
    "",
    "------------------------------",
    "## Staging & Committing",
    "",
    "### Stage changes",
    "git add <file>",
    "git add .                                             # stage all changes",
    "git add -p                                            # stage interactively (hunks)",
    "git restore --staged <file>                           # unstage a file",
    "git reset <file>                                      # unstage (older style)",
    "",
    "### Commit",
    "git commit -m \"message\"",
    "git commit                                            # open editor",
    "git commit -am \"message\"                             # stage tracked files + commit",
    "git commit --amend                                    # edit last commit (message + content)",
    "git commit --amend --no-edit                          # amend without changing message",
    "",
    "### Fixup/squash workflows",
    "git commit --fixup <commit>",
    "git rebase -i --autosquash <base>",
    "",
    "------------------------------",
    "## Branching",
    "",
    "### List/create/delete",
    "git branch",
    "git branch -a                                         # local + remote",
    "git branch <name>",
    "git branch -d <name>                                  # delete (safe)",
    "git branch -D <name>                                  # delete (force)",
    "",
    "### Switch",
    "git switch <branch>",
    "git switch -c <new-branch>                            # create + switch",
    "git switch -                                          # previous branch",
    "",
    "### Rename",
    "git branch -m <new-name>                              # rename current branch",
    "git branch -m <old> <new>",
    "",
    "### Track remotes",
    "git branch -u origin/<branch>                         # set upstream",
    "git switch -c <branch> --track origin/<branch>",
    "",
    "------------------------------",
    "## Worktrees",
    "",
    "git worktree list                                     # show linked working trees",
    "git worktree add ../repo-feature feature-branch       # new worktree for existing branch",
    "git worktree add -b feature-x ../repo-feature-x       # create branch + worktree together",
    "git worktree add ../repo-hotfix --detach <commit>     # detached HEAD worktree",
    "git worktree remove ../repo-feature                   # remove worktree metadata + dir",
    "git worktree move ../repo-feature ../repo-feature-old # move a worktree",
    "git worktree prune                                    # clean stale worktree records",
    "git branch -d feature-branch                          # delete branch after removing worktree",
    "",
    "------------------------------",
    "## Remote / Fetch / Pull / Push",
    "",
    "### Remotes",
    "git remote -v",
    "git remote add origin <url>",
    "git remote set-url origin <url>",
    "",
    "### Fetch",
    "git fetch",
    "git fetch --all --prune                               # prune deleted remote refs",
    "git fetch origin <branch>",
    "",
    "### Pull",
    "git pull                                              # merge by default (unless configured)",
    "git pull --rebase                                     # rebase onto upstream",
    "git pull --ff-only                                    # only fast-forward",
    "",
    "### Push",
    "git push",
    "git push -u origin <branch>                           # set upstream on first push",
    "git push origin :<branch>                             # delete remote branch",
    "git push --force-with-lease                           # safer force push",
    "",
    "------------------------------",
    "## Merge / Rebase (and conflict handling)",
    "",
    "### Merge",
    "git merge <branch>",
    "git merge --no-ff <branch>                            # keep merge commit",
    "git merge --squash <branch>                           # merge but create 1 squashed commit",
    "git merge --abort                                     # abort merge with conflicts",
    "",
    "### Rebase",
    "git rebase <branch>                                   # rebase current onto <branch>",
    "git rebase -i <base>                                  # interactive rebase",
    "git rebase --onto <newbase> <upstream> <branch>       # advanced move",
    "git rebase --continue",
    "git rebase --abort",
    "git rebase --skip",
    "",
    "### Conflict helpers",
    "git status                                            # see conflict paths",
    "git diff                                              # view conflict markers",
    "git checkout --theirs <file>                          # during merge/rebase (use with care)",
    "git checkout --ours <file>                            # during merge/rebase (use with care)",
    "git add <file>                                        # mark resolved",
    "",
    "------------------------------",
    "## Stash",
    "",
    "git stash                                             # stash tracked changes",
    "git stash -u                                          # include untracked",
    "git stash -a                                          # include ignored too (rare)",
    "git stash push -m \"msg\"                             # named stash",
    "git stash list",
    "git stash show -p stash@{0}                           # patch view",
    "git stash apply stash@{0}",
    "git stash pop                                         # apply + drop",
    "git stash drop stash@{0}",
    "git stash clear",
    "",
    "------------------------------",
    "## Undoing & Recovery (read this carefully)",
    "",
    "### Working tree (discard changes)",
    "git restore <file>                                    # discard unstaged changes to file",
    "git restore .                                         # discard all unstaged changes",
    "",
    "### Unstage",
    "git restore --staged <file>",
    "git reset <file>",
    "",
    "### Move HEAD/branch pointer (reset)",
    "# reset affects your branch pointer and sometimes index/working tree:",
    "git reset --soft HEAD~1                               # keep changes staged",
    "git reset --mixed HEAD~1                              # keep changes unstaged (default)",
    "git reset --hard HEAD~1                               # discard changes (danger)",
    "",
    "### Safe history change (revert)",
    "# revert makes a new commit that undoes another commit (safe for shared branches):",
    "git revert <commit>",
    "git revert <oldest>^..<newest>                        # revert a range (creates multiple)",
    "",
    "### Recover “lost” commits",
    "git reflog                                            # history of where HEAD/branches pointed",
    "git reflog show <branch>",
    "git checkout <reflog-hash>                            # inspect state",
    "git reset --hard <reflog-hash>                        # restore (danger)",
    "",
    "------------------------------",
    "## Cherry-pick",
    "",
    "git cherry-pick <commit>",
    "git cherry-pick <a>^..<b>                             # pick range (inclusive)",
    "git cherry-pick --continue",
    "git cherry-pick --abort",
    "",
    "------------------------------",
    "## Bisect (find the commit that introduced a bug)",
    "",
    "git bisect start",
    "git bisect bad                                        # current commit is bad",
    "git bisect good <commit>                              # known good commit",
    "git bisect run <test-script>                          # automate",
    "git bisect reset",
    "",
    "------------------------------",
    "## Tags & Releases",
    "",
    "git tag                                               # list tags",
    "git tag <name>                                        # lightweight tag",
    "git tag -a <name> -m \"msg\"                           # annotated tag (preferred for releases)",
    "git show <tag>",
    "git push origin <tag>",
    "git push origin --tags",
    "git tag -d <tag>",
    "git push origin :refs/tags/<tag>                      # delete remote tag",
    "",
    "------------------------------",
    "## Submodules",
    "",
    "git submodule add <url> <path>",
    "git submodule update --init --recursive",
    "git submodule foreach git pull                        # update each submodule",
    "git diff --submodule",
    "",
    "------------------------------",
    "## Large Files (Git LFS)",
    "",
    "git lfs install",
    "git lfs track \"*.psd\"",
    "git add .gitattributes",
    "git lfs ls-files",
    "",
    "------------------------------",
    "## Clean / Maintenance",
    "",
    "git clean -nfd                                        # preview removing untracked files/dirs",
    "git clean -fd                                         # remove untracked files/dirs",
    "git gc                                                # housekeeping",
    "git fsck                                              # verify object database",
    "",
    "------------------------------",
    "## Handy One-liners",
    "",
    "git log --pretty=format:\"%h %ad %an %s\" --date=short",
    "git log --graph --decorate --oneline --all",
    "git show --name-only <commit>",
    "git diff --name-only",
    "git branch --sort=-committerdate",
    "git for-each-ref --sort=-committerdate --format='%(refname:short) %(committerdate:short)' refs/heads/",
    "",
    "------------------------------",
    "## Common Fix Patterns",
    "",
    "### I committed to the wrong branch",
    "git switch correct-branch",
    "git cherry-pick <commit>",
    "git switch wrong-branch",
    "git reset --hard HEAD~1                               # if safe & not pushed",
    "",
    "### I want to split a commit",
    "git reset --mixed HEAD~1",
    "git add -p",
    "git commit -m \"part 1\"",
    "git add -p",
    "git commit -m \"part 2\"",
    "",
    "### My branch is behind main (rebase workflow)",
    "git fetch origin",
    "git rebase origin/main",
    "git push --force-with-lease                           # if branch already pushed",
    "",
    "### I need to undo a pushed commit safely",
    "git revert <commit>",
    "",
    "",
    "----",
    "End. (Feel free to customize this cheat sheet to your team’s workflow.)",
  }

  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)

  -- Make buffer read-only after population
  vim.bo[buf].modifiable = false
  vim.bo[buf].readonly = true

  -- Nice-to-have options
  vim.wo.wrap = false
  vim.wo.number = false
  vim.wo.relativenumber = false
end, {})
